#!/usr/bin/env bash
# archive-ai-renders.sh (comprehensive)
# Moves ALL AI-pipeline images out of /img/ into ~/code/_image-gen/archive/barranquilla/
# Covers: -place-, -food-, -venue-, -section-N, -hero, -pexels-generic
# Matching HTML blocks already stripped.
#
# Usage:  bash scripts/archive-ai-renders.sh

set -e
cd "$(dirname "$0")/.."

DEST="$HOME/code/_image-gen/archive/barranquilla"
mkdir -p "$DEST"

moved=0
size_bytes=0
while IFS= read -r f; do
  [ -z "$f" ] && continue
  if [ -f "img/$f" ]; then
    sz=$(stat -f%z "img/$f" 2>/dev/null || stat -c%s "img/$f" 2>/dev/null || echo 0)
    git rm -q --cached -- "img/$f" 2>/dev/null || true
    mv -- "img/$f" "$DEST/$f"
    moved=$((moved + 1))
    size_bytes=$((size_bytes + sz))
  fi
done <<'FILES'
alto-prado-place-buenavista.jpg
alto-prado-place-buenavista.webp
alto-prado-place-riomar.jpg
alto-prado-place-riomar.webp
alto-prado-place-tree-lined-median-of-carrera-46.jpg
alto-prado-place-tree-lined-median-of-carrera-46.webp
altos-de-riomar-place-el-golf.jpg
altos-de-riomar-place-el-golf.webp
altos-de-riomar-place-puerto-colombia.jpg
altos-de-riomar-place-puerto-colombia.webp
barranquilla-airport-guide-place-barranquilla.jpg
barranquilla-airport-guide-place-barranquilla.webp
barranquilla-airport-guide-place-buenavista.jpg
barranquilla-airport-guide-place-buenavista.webp
barranquilla-airport-guide-place-cali.jpg
barranquilla-airport-guide-place-cali.webp
barranquilla-airport-guide-place-cartagena.jpg
barranquilla-airport-guide-place-cartagena.webp
barranquilla-airport-guide-place-centro-historico.jpg
barranquilla-airport-guide-place-centro-historico.webp
barranquilla-airport-guide-place-ernesto-cortissoz-international-airport.jpg
barranquilla-airport-guide-place-ernesto-cortissoz-international-airport.webp
barranquilla-airport-guide-place-fort-lauderdale.jpg
barranquilla-airport-guide-place-fort-lauderdale.webp
barranquilla-airport-guide-place-malecon.jpg
barranquilla-airport-guide-place-malecon.webp
barranquilla-airport-guide-place-palomino.jpg
barranquilla-airport-guide-place-palomino.webp
barranquilla-airport-guide-place-panama-city.jpg
barranquilla-airport-guide-place-panama-city.webp
barranquilla-airport-guide-place-puerto-colombia.jpg
barranquilla-airport-guide-place-puerto-colombia.webp
barranquilla-airport-guide-place-san-andres.jpg
barranquilla-airport-guide-place-san-andres.webp
barranquilla-airport-guide-place-santa-marta.jpg
barranquilla-airport-guide-place-santa-marta.webp
barranquilla-airport-guide-place-soledad.jpg
barranquilla-airport-guide-place-soledad.webp
barranquilla-airport-guide-place-tolu.jpg
barranquilla-airport-guide-place-tolu.webp
barranquilla-airport-guide-place-villa-country.jpg
barranquilla-airport-guide-place-villa-country.webp
barranquilla-airport-guide-place-villa-santos.jpg
barranquilla-airport-guide-place-villa-santos.webp
barranquilla-bocas-de-cenizas-tour-place-barranquilla.jpg
barranquilla-bocas-de-cenizas-tour-place-barranquilla.webp
barranquilla-bocas-de-cenizas-tour-place-bocas-de-cenizas.jpg
barranquilla-bocas-de-cenizas-tour-place-bocas-de-cenizas.webp
barranquilla-bocas-de-cenizas-tour-place-caribbean-sea.jpg
barranquilla-bocas-de-cenizas-tour-place-caribbean-sea.webp
barranquilla-bocas-de-cenizas-tour-place-cartagena.jpg
barranquilla-bocas-de-cenizas-tour-place-cartagena.webp
barranquilla-bocas-de-cenizas-tour-place-gran-malecon.jpg
barranquilla-bocas-de-cenizas-tour-place-gran-malecon.webp
barranquilla-bocas-de-cenizas-tour-place-magdalena-river.jpg
barranquilla-bocas-de-cenizas-tour-place-magdalena-river.webp
barranquilla-bocas-de-cenizas-tour-place-puerto-colombia.jpg
barranquilla-bocas-de-cenizas-tour-place-puerto-colombia.webp
barranquilla-bocas-de-cenizas-tour-place-santa-marta.jpg
barranquilla-bocas-de-cenizas-tour-place-santa-marta.webp
barranquilla-caribbean-night-break-tour-place-el-prado.jpg
barranquilla-caribbean-night-break-tour-place-el-prado.webp
barranquilla-caribbean-night-break-tour-place-gran-malecon.jpg
barranquilla-caribbean-night-break-tour-place-gran-malecon.webp
barranquilla-caribbean-night-break-tour-place-puerto-colombia.jpg
barranquilla-caribbean-night-break-tour-place-puerto-colombia.webp
barranquilla-carnival-complete-guide-place-alto-prado.jpg
barranquilla-carnival-complete-guide-place-alto-prado.webp
barranquilla-carnival-complete-guide-place-barrio-abajo.jpg
barranquilla-carnival-complete-guide-place-barrio-abajo.webp
barranquilla-carnival-complete-guide-place-centro.jpg
barranquilla-carnival-complete-guide-place-centro.webp
barranquilla-carnival-complete-guide-place-villa-country.jpg
barranquilla-carnival-complete-guide-place-villa-country.webp
barranquilla-food-tour-downtown-food-corozo.jpg
barranquilla-food-tour-downtown-food-corozo.webp
barranquilla-food-tour-downtown-food-guanabana.jpg
barranquilla-food-tour-downtown-food-guanabana.webp
barranquilla-food-tour-downtown-food-maracuya.jpg
barranquilla-food-tour-downtown-food-maracuya.webp
barranquilla-food-tour-downtown-place-el-centro.jpg
barranquilla-food-tour-downtown-place-el-centro.webp
barranquilla-guide-place-bello-horizonte.jpg
barranquilla-guide-place-bello-horizonte.webp
barranquilla-guide-place-ciudad-jardin.jpg
barranquilla-guide-place-ciudad-jardin.webp
barranquilla-guide-place-el-prado.jpg
barranquilla-guide-place-el-prado.webp
barranquilla-guide-place-manga.jpg
barranquilla-guide-place-manga.webp
barranquilla-guide-place-zona-norte.jpg
barranquilla-guide-place-zona-norte.webp
barranquilla-mallorquin-ecopark-tour-place-bocas-de-cenizas-viewpoint.jpg
barranquilla-mallorquin-ecopark-tour-place-bocas-de-cenizas-viewpoint.webp
barranquilla-mallorquin-ecopark-tour-place-caribbean-sea.jpg
barranquilla-mallorquin-ecopark-tour-place-caribbean-sea.webp
barranquilla-mallorquin-ecopark-tour-place-cienaga-grande-ecosystem.jpg
barranquilla-mallorquin-ecopark-tour-place-cienaga-grande-ecosystem.webp
barranquilla-mallorquin-ecopark-tour-place-magdalena-river.jpg
barranquilla-mallorquin-ecopark-tour-place-magdalena-river.webp
barranquilla-mallorquin-ecopark-tour-place-mallorquin-cienaga.jpg
barranquilla-mallorquin-ecopark-tour-place-mallorquin-cienaga.webp
barranquilla-malls-place-buenavista-corridor.jpg
barranquilla-malls-place-buenavista-corridor.webp
barranquilla-malls-place-villa-country-neighborhood.jpg
barranquilla-malls-place-villa-country-neighborhood.webp
barranquilla-malls-section-8.jpg
barranquilla-malls-section-8.webp
barranquilla-nightlife-bars-clubs-food-aguardiente.jpg
barranquilla-nightlife-bars-clubs-food-aguardiente.webp
barranquilla-nightlife-bars-clubs-food-arepa-de-huevo.jpg
barranquilla-nightlife-bars-clubs-food-arepa-de-huevo.webp
barranquilla-nightlife-bars-clubs-place-alto-prado.jpg
barranquilla-nightlife-bars-clubs-place-alto-prado.webp
barranquilla-nightlife-bars-clubs-place-carrera-43-el-prado.jpg
barranquilla-nightlife-bars-clubs-place-carrera-43-el-prado.webp
barranquilla-nightlife-bars-clubs-place-centro.jpg
barranquilla-nightlife-bars-clubs-place-centro.webp
barranquilla-nightlife-bars-clubs-place-el-prado.jpg
barranquilla-nightlife-bars-clubs-place-el-prado.webp
barranquilla-nightlife-bars-clubs-place-paseo-bolivar.jpg
barranquilla-nightlife-bars-clubs-place-paseo-bolivar.webp
barranquilla-nightlife-bars-clubs-place-villa-country.jpg
barranquilla-nightlife-bars-clubs-place-villa-country.webp
barranquilla-private-bike-tour-place-barrio-abajo.jpg
barranquilla-private-bike-tour-place-barrio-abajo.webp
barranquilla-private-bike-tour-place-el-prado-historic-district.jpg
barranquilla-private-bike-tour-place-el-prado-historic-district.webp
barranquilla-private-bike-tour-place-gran-malecon-del-rio.jpg
barranquilla-private-bike-tour-place-gran-malecon-del-rio.webp
barranquilla-private-bike-tour-place-magdalena-river.jpg
barranquilla-private-bike-tour-place-magdalena-river.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-arepa-de-huevo.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-arepa-de-huevo.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-arepa-paisa.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-arepa-paisa.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-bollo.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-bollo.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-butifarra.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-butifarra.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-changua.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-changua.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-mojarra-frita.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-mojarra-frita.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-sancocho-de-pescado.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-food-sancocho-de-pescado.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-alto-prado.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-alto-prado.webp
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-el-prado.jpg
barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-el-prado.webp
barranquilla-walking-tour-el-prado-place-cartagenas-old-city.jpg
barranquilla-walking-tour-el-prado-place-cartagenas-old-city.webp
barranquilla-walking-tour-el-prado-place-el-prado.jpg
barranquilla-walking-tour-el-prado-place-el-prado.webp
barranquilla-walking-tour-el-prado-place-san-basilio-de-palenque.jpg
barranquilla-walking-tour-el-prado-place-san-basilio-de-palenque.webp
barranquilla-wedding-guide-2026-food-aguardiente.jpg
barranquilla-wedding-guide-2026-food-aguardiente.webp
barranquilla-wedding-guide-2026-food-bandeja-paisa.jpg
barranquilla-wedding-guide-2026-food-bandeja-paisa.webp
barranquilla-wedding-guide-2026-food-patacones.jpg
barranquilla-wedding-guide-2026-food-patacones.webp
barranquilla-wedding-guide-2026-food-ron-medellin.jpg
barranquilla-wedding-guide-2026-food-ron-medellin.webp
barranquilla-wedding-guide-2026-food-ron-viejo-de-caldas.jpg
barranquilla-wedding-guide-2026-food-ron-viejo-de-caldas.webp
barranquilla-wedding-guide-2026-food-rum-and-coke.jpg
barranquilla-wedding-guide-2026-food-rum-and-coke.webp
barranquilla-wedding-guide-2026-place-alto-prado.jpg
barranquilla-wedding-guide-2026-place-alto-prado.webp
barranquilla-wedding-guide-2026-place-cartagena-ctg.jpg
barranquilla-wedding-guide-2026-place-cartagena-ctg.webp
barranquilla-wedding-guide-2026-place-ernesto-cortissoz-international-airport.jpg
barranquilla-wedding-guide-2026-place-ernesto-cortissoz-international-airport.webp
barranquilla-wedding-guide-2026-place-galapa.jpg
barranquilla-wedding-guide-2026-place-galapa.webp
barranquilla-wedding-guide-2026-place-gran-malecon-del-rio.jpg
barranquilla-wedding-guide-2026-place-gran-malecon-del-rio.webp
barranquilla-wedding-guide-2026-place-la-puerta-de-oro.jpg
barranquilla-wedding-guide-2026-place-la-puerta-de-oro.webp
barranquilla-wedding-guide-2026-place-puerto-colombia.jpg
barranquilla-wedding-guide-2026-place-puerto-colombia.webp
barranquilla-wedding-guide-2026-place-puerto-velero.jpg
barranquilla-wedding-guide-2026-place-puerto-velero.webp
barranquilla-wedding-guide-2026-place-salgar.jpg
barranquilla-wedding-guide-2026-place-salgar.webp
barranquilla-wedding-guide-2026-place-tubara.jpg
barranquilla-wedding-guide-2026-place-tubara.webp
barranquilla-wedding-guide-2026-place-usiacuri.jpg
barranquilla-wedding-guide-2026-place-usiacuri.webp
barranquilla-wedding-guide-2026-place-villa-santos.jpg
barranquilla-wedding-guide-2026-place-villa-santos.webp
barranquilla-with-kids-family-guide-2026-place-alto-prado.jpg
barranquilla-with-kids-family-guide-2026-place-alto-prado.webp
barranquilla-with-kids-family-guide-2026-place-el-centro.jpg
barranquilla-with-kids-family-guide-2026-place-el-centro.webp
barranquilla-with-kids-family-guide-2026-place-el-golf.jpg
barranquilla-with-kids-family-guide-2026-place-el-golf.webp
barranquilla-with-kids-family-guide-2026-place-gran-malecon-del-rio.jpg
barranquilla-with-kids-family-guide-2026-place-gran-malecon-del-rio.webp
barranquilla-with-kids-family-guide-2026-place-parque-metropolitano.jpg
barranquilla-with-kids-family-guide-2026-place-parque-metropolitano.webp
barranquilla-with-kids-family-guide-2026-place-parque-sagrado-corazon.jpg
barranquilla-with-kids-family-guide-2026-place-parque-sagrado-corazon.webp
barranquilla-with-kids-family-guide-2026-place-parque-venezuela.jpg
barranquilla-with-kids-family-guide-2026-place-parque-venezuela.webp
barranquilla-with-kids-family-guide-2026-place-pradomar.jpg
barranquilla-with-kids-family-guide-2026-place-pradomar.webp
barranquilla-with-kids-family-guide-2026-place-puerto-colombia.jpg
barranquilla-with-kids-family-guide-2026-place-puerto-colombia.webp
barranquilla-with-kids-family-guide-2026-place-riomar.jpg
barranquilla-with-kids-family-guide-2026-place-riomar.webp
barranquilla-with-kids-family-guide-2026-place-salgar.jpg
barranquilla-with-kids-family-guide-2026-place-salgar.webp
barranquilla-with-kids-family-guide-2026-place-santa-marta.jpg
barranquilla-with-kids-family-guide-2026-place-santa-marta.webp
barranquilla-with-kids-family-guide-2026-place-villa-santos.jpg
barranquilla-with-kids-family-guide-2026-place-villa-santos.webp
best-bars-craft-drinks-barranquilla-food-dulcinea-brown-ale.jpg
best-bars-craft-drinks-barranquilla-food-dulcinea-brown-ale.webp
best-bars-craft-drinks-barranquilla-food-the-boka-legend.jpg
best-bars-craft-drinks-barranquilla-food-the-boka-legend.webp
best-coworking-spaces-barranquilla-place-el-poblado.jpg
best-coworking-spaces-barranquilla-place-el-poblado.webp
best-coworking-spaces-barranquilla-place-el-prado.jpg
best-coworking-spaces-barranquilla-place-el-prado.webp
best-coworking-spaces-barranquilla-place-zona-norte.jpg
best-coworking-spaces-barranquilla-place-zona-norte.webp
best-family-restaurants-barranquilla-food-arroz-rozzo-de-mariscos.jpg
best-family-restaurants-barranquilla-food-arroz-rozzo-de-mariscos.webp
best-family-restaurants-barranquilla-food-camarones-al-ajo.jpg
best-family-restaurants-barranquilla-food-camarones-al-ajo.webp
best-family-restaurants-barranquilla-food-coconut-rice.jpg
best-family-restaurants-barranquilla-food-coconut-rice.webp
best-family-restaurants-barranquilla-food-comida-corriente.jpg
best-family-restaurants-barranquilla-food-comida-corriente.webp
best-family-restaurants-barranquilla-food-margherita.jpg
best-family-restaurants-barranquilla-food-margherita.webp
best-family-restaurants-barranquilla-food-mojarra-frita.jpg
best-family-restaurants-barranquilla-food-mojarra-frita.webp
best-gyms-in-barranquilla-place-alto-prado.jpg
best-gyms-in-barranquilla-place-alto-prado.webp
best-gyms-in-barranquilla-place-barranquilla.jpg
best-gyms-in-barranquilla-place-barranquilla.webp
best-gyms-in-barranquilla-place-el-prado.jpg
best-gyms-in-barranquilla-place-el-prado.webp
best-gyms-in-barranquilla-place-villa-campestre.jpg
best-gyms-in-barranquilla-place-villa-campestre.webp
best-gyms-in-barranquilla-place-villa-country.jpg
best-gyms-in-barranquilla-place-villa-country.webp
best-night-out-barranquilla-food-boka-legend-cocktail.jpg
best-night-out-barranquilla-food-boka-legend-cocktail.webp
best-night-out-barranquilla-food-dulcinea.jpg
best-night-out-barranquilla-food-dulcinea.webp
best-night-out-barranquilla-place-alto-prado.jpg
best-night-out-barranquilla-place-alto-prado.webp
best-night-out-barranquilla-place-el-prado.jpg
best-night-out-barranquilla-place-el-prado.webp
best-night-out-barranquilla-place-riomar.jpg
best-night-out-barranquilla-place-riomar.webp
best-restaurants-with-children-barranquilla-food-costena-burger.jpg
best-restaurants-with-children-barranquilla-food-costena-burger.webp
best-restaurants-with-children-barranquilla-food-frozo-malt-shake.jpg
best-restaurants-with-children-barranquilla-food-frozo-malt-shake.webp
best-restaurants-with-children-barranquilla-food-passion-fruit.jpg
best-restaurants-with-children-barranquilla-food-passion-fruit.webp
best-restaurants-with-children-barranquilla-food-zapote.jpg
best-restaurants-with-children-barranquilla-food-zapote.webp
best-restaurants-with-children-barranquilla-place-gran-malecon.jpg
best-restaurants-with-children-barranquilla-place-gran-malecon.webp
best-tours-experiences-barranquilla-place-banco-de-la-republica-building.jpg
best-tours-experiences-barranquilla-place-banco-de-la-republica-building.webp
best-tours-experiences-barranquilla-place-barranquilla-carnival.jpg
best-tours-experiences-barranquilla-place-barranquilla-carnival.webp
best-tours-experiences-barranquilla-place-barranquilla.jpg
best-tours-experiences-barranquilla-place-barranquilla.webp
best-tours-experiences-barranquilla-place-catedral-metropolitana.jpg
best-tours-experiences-barranquilla-place-catedral-metropolitana.webp
best-tours-experiences-barranquilla-place-cienaga-grande-wetlands.jpg
best-tours-experiences-barranquilla-place-cienaga-grande-wetlands.webp
best-tours-experiences-barranquilla-place-el-centro.jpg
best-tours-experiences-barranquilla-place-el-centro.webp
best-tours-experiences-barranquilla-place-el-prado-neighbourhood.jpg
best-tours-experiences-barranquilla-place-el-prado-neighbourhood.webp
best-tours-experiences-barranquilla-place-puerto-colombia.jpg
best-tours-experiences-barranquilla-place-puerto-colombia.webp
buenavista-place-buenavista.jpg
buenavista-place-buenavista.webp
buenavista-place-calle-98-corridor.jpg
buenavista-place-calle-98-corridor.webp
buenavista-place-el-golf.jpg
buenavista-place-el-golf.webp
buenavista-place-el-prado-neighborhood.jpg
buenavista-place-el-prado-neighborhood.webp
buenavista-place-puerto-colombia-beaches.jpg
buenavista-place-puerto-colombia-beaches.webp
buenavista-place-riomar.jpg
buenavista-place-riomar.webp
buenavista-place-villa-country.jpg
buenavista-place-villa-country.webp
ciudad-jardin-place-alto-prado.jpg
ciudad-jardin-place-alto-prado.webp
ciudad-jardin-place-villa-country.jpg
ciudad-jardin-place-villa-country.webp
colombia-travel-insurance-guide-place-barranquilla.jpg
colombia-travel-insurance-guide-place-barranquilla.webp
colombia-travel-insurance-guide-place-ernesto-cortissoz-international-airport.jpg
colombia-travel-insurance-guide-place-ernesto-cortissoz-international-airport.webp
colombia-travel-insurance-guide-place-sierra-nevada.jpg
colombia-travel-insurance-guide-place-sierra-nevada.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-alto-prado.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-alto-prado.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-altos-del-limon.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-altos-del-limon.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-boston-neighborhood.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-boston-neighborhood.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-ciudad-jardin.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-ciudad-jardin.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-granadillo.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-granadillo.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-mercado-de-barranquilla.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-mercado-de-barranquilla.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-mercado-publico-de-la-45.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-mercado-publico-de-la-45.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-country.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-country.webp
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-santos.jpg
cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-santos.webp
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-altos-del-prado-barranquilla.jpg
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-altos-del-prado-barranquilla.webp
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-barrio-abajo-barranquilla.jpg
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-barrio-abajo-barranquilla.webp
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-el-prado-barranquilla.jpg
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-el-prado-barranquilla.webp
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-villa-country-barranquilla.jpg
dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-villa-country-barranquilla.webp
day-trips-from-barranquilla-place-bocas-de-cenizas.jpg
day-trips-from-barranquilla-place-bocas-de-cenizas.webp
day-trips-from-barranquilla-place-cartagena.jpg
day-trips-from-barranquilla-place-cartagena.webp
day-trips-from-barranquilla-place-cienaga-grande-de-santa-marta.jpg
day-trips-from-barranquilla-place-cienaga-grande-de-santa-marta.webp
day-trips-from-barranquilla-place-mallorquin-eco-park.jpg
day-trips-from-barranquilla-place-mallorquin-eco-park.webp
day-trips-from-barranquilla-place-nueva-venecia.jpg
day-trips-from-barranquilla-place-nueva-venecia.webp
day-trips-from-barranquilla-place-puerto-colombia.jpg
day-trips-from-barranquilla-place-puerto-colombia.webp
day-trips-from-barranquilla-place-ruta-del-girasol-sunflower-fields.jpg
day-trips-from-barranquilla-place-ruta-del-girasol-sunflower-fields.webp
day-trips-from-barranquilla-place-san-basilio-de-palenque.jpg
day-trips-from-barranquilla-place-san-basilio-de-palenque.webp
day-trips-from-barranquilla-place-santa-marta.jpg
day-trips-from-barranquilla-place-santa-marta.webp
day-trips-from-barranquilla-place-sierra-nevada-de-santa-marta-mountains.jpg
day-trips-from-barranquilla-place-sierra-nevada-de-santa-marta-mountains.webp
day-trips-from-barranquilla-place-tayrona-national-park.jpg
day-trips-from-barranquilla-place-tayrona-national-park.webp
day-trips-from-barranquilla-place-walled-city-of-cartagena.jpg
day-trips-from-barranquilla-place-walled-city-of-cartagena.webp
driving-in-colombia-barranquilla-2026-guide-place-atlantico.jpg
driving-in-colombia-barranquilla-2026-guide-place-atlantico.webp
driving-in-colombia-barranquilla-2026-guide-place-barranquilla.jpg
driving-in-colombia-barranquilla-2026-guide-place-barranquilla.webp
driving-in-colombia-barranquilla-2026-guide-place-calle-30.jpg
driving-in-colombia-barranquilla-2026-guide-place-calle-30.webp
driving-in-colombia-barranquilla-2026-guide-place-calle-84.jpg
driving-in-colombia-barranquilla-2026-guide-place-calle-84.webp
driving-in-colombia-barranquilla-2026-guide-place-carrera-51b.jpg
driving-in-colombia-barranquilla-2026-guide-place-carrera-51b.webp
driving-in-colombia-barranquilla-2026-guide-place-pradomar.jpg
driving-in-colombia-barranquilla-2026-guide-place-pradomar.webp
driving-in-colombia-barranquilla-2026-guide-place-puerto-colombia.jpg
driving-in-colombia-barranquilla-2026-guide-place-puerto-colombia.webp
driving-in-colombia-barranquilla-2026-guide-place-salgar.jpg
driving-in-colombia-barranquilla-2026-guide-place-salgar.webp
driving-in-colombia-barranquilla-2026-guide-place-santa-marta.jpg
driving-in-colombia-barranquilla-2026-guide-place-santa-marta.webp
driving-in-colombia-barranquilla-2026-guide-place-via-40.jpg
driving-in-colombia-barranquilla-2026-guide-place-via-40.webp
driving-in-colombia-barranquilla-2026-guide-place-villa-campestre.jpg
driving-in-colombia-barranquilla-2026-guide-place-villa-campestre.webp
driving-in-colombia-barranquilla-2026-guide-place-zona-norte.jpg
driving-in-colombia-barranquilla-2026-guide-place-zona-norte.webp
el-golf-place-el-golf.jpg
el-golf-place-el-golf.webp
el-golf-place-el-prado.jpg
el-golf-place-el-prado.webp
el-prado-hotel-place-buenavista.jpg
el-prado-hotel-place-buenavista.webp
el-prado-hotel-place-carrera-53.jpg
el-prado-hotel-place-carrera-53.webp
el-prado-hotel-place-el-prado-neighborhood.jpg
el-prado-hotel-place-el-prado-neighborhood.webp
el-prado-hotel-place-via-40.jpg
el-prado-hotel-place-via-40.webp
el-prado-place-barrio-abajo.jpg
el-prado-place-barrio-abajo.webp
el-prado-place-el-prado.jpg
el-prado-place-el-prado.webp
el-tabor-place-buenavista.jpg
el-tabor-place-buenavista.webp
el-tabor-place-calle-72.jpg
el-tabor-place-calle-72.webp
el-tabor-place-carrera-46.jpg
el-tabor-place-carrera-46.webp
el-tabor-place-el-golf.jpg
el-tabor-place-el-golf.webp
el-tabor-place-el-tabor.jpg
el-tabor-place-el-tabor.webp
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-el-prado-neighborhood.jpg
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-el-prado-neighborhood.webp
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-malecon.jpg
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-malecon.webp
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-parque-metropolitano.jpg
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-parque-metropolitano.webp
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-villa-country-neighborhood.jpg
expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-villa-country-neighborhood.webp
fun-things-to-do-in-barranquilla-as-a-group-food-arepas-de-huevo.jpg
fun-things-to-do-in-barranquilla-as-a-group-food-arepas-de-huevo.webp
fun-things-to-do-in-barranquilla-as-a-group-place-alameda-del-rio.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-alameda-del-rio.webp
fun-things-to-do-in-barranquilla-as-a-group-place-bocas-de-ceniza.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-bocas-de-ceniza.webp
fun-things-to-do-in-barranquilla-as-a-group-place-el-prado.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-el-prado.webp
fun-things-to-do-in-barranquilla-as-a-group-place-gran-malecon-del-rio.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-gran-malecon-del-rio.webp
fun-things-to-do-in-barranquilla-as-a-group-place-magdalena.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-magdalena.webp
fun-things-to-do-in-barranquilla-as-a-group-place-plaza-de-la-paz.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-plaza-de-la-paz.webp
fun-things-to-do-in-barranquilla-as-a-group-place-puerto-colombia.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-puerto-colombia.webp
fun-things-to-do-in-barranquilla-as-a-group-place-puerto-mocho-beach.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-puerto-mocho-beach.webp
fun-things-to-do-in-barranquilla-as-a-group-place-via-40.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-via-40.webp
fun-things-to-do-in-barranquilla-as-a-group-place-villa-country.jpg
fun-things-to-do-in-barranquilla-as-a-group-place-villa-country.webp
fun-things-to-do-in-barranquilla-as-a-group-section-7.jpg
fun-things-to-do-in-barranquilla-as-a-group-section-7.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-banco-de-la-republica-building.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-banco-de-la-republica-building.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-cartagena.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-cartagena.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-catedral-metropolitana.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-catedral-metropolitana.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-downtown-barranquilla.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-downtown-barranquilla.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-el-prado-area.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-el-prado-area.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-gran-malecon-del-rio.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-gran-malecon-del-rio.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-magdalena-river.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-magdalena-river.webp
gran-malecon-carnaval-museum-barranquilla-city-tour-place-pasaje-bolivar.jpg
gran-malecon-carnaval-museum-barranquilla-city-tour-place-pasaje-bolivar.webp
healthcare-barranquilla-place-alto-prado.jpg
healthcare-barranquilla-place-alto-prado.webp
healthcare-barranquilla-place-riomar.jpg
healthcare-barranquilla-place-riomar.webp
healthcare-barranquilla-place-villa-country.jpg
healthcare-barranquilla-place-villa-country.webp
healthcare-barranquilla-place-villa-santos.jpg
healthcare-barranquilla-place-villa-santos.webp
housing-renting-barranquilla-place-alto-prado.jpg
housing-renting-barranquilla-place-alto-prado.webp
housing-renting-barranquilla-place-altos-de-riomar.jpg
housing-renting-barranquilla-place-altos-de-riomar.webp
housing-renting-barranquilla-place-altos-del-limon.jpg
housing-renting-barranquilla-place-altos-del-limon.webp
housing-renting-barranquilla-place-buenavista.jpg
housing-renting-barranquilla-place-buenavista.webp
housing-renting-barranquilla-place-el-prado.jpg
housing-renting-barranquilla-place-el-prado.webp
housing-renting-barranquilla-place-granadillo.jpg
housing-renting-barranquilla-place-granadillo.webp
housing-renting-barranquilla-place-nuevo-horizonte.jpg
housing-renting-barranquilla-place-nuevo-horizonte.webp
housing-renting-barranquilla-place-paraiso.jpg
housing-renting-barranquilla-place-paraiso.webp
housing-renting-barranquilla-place-riomar.jpg
housing-renting-barranquilla-place-riomar.webp
housing-renting-barranquilla-place-via-40.jpg
housing-renting-barranquilla-place-via-40.webp
housing-renting-barranquilla-place-villa-campestre.jpg
housing-renting-barranquilla-place-villa-campestre.webp
housing-renting-barranquilla-place-villa-country.jpg
housing-renting-barranquilla-place-villa-country.webp
housing-renting-barranquilla-place-villa-santos.jpg
housing-renting-barranquilla-place-villa-santos.webp
is-barranquilla-safe-honest-answer-2026-place-alto-prado.jpg
is-barranquilla-safe-honest-answer-2026-place-alto-prado.webp
is-barranquilla-safe-honest-answer-2026-place-altos-del-limon.jpg
is-barranquilla-safe-honest-answer-2026-place-altos-del-limon.webp
is-barranquilla-safe-honest-answer-2026-place-barrio-abajo.jpg
is-barranquilla-safe-honest-answer-2026-place-barrio-abajo.webp
is-barranquilla-safe-honest-answer-2026-place-boston.jpg
is-barranquilla-safe-honest-answer-2026-place-boston.webp
is-barranquilla-safe-honest-answer-2026-place-buenavista.jpg
is-barranquilla-safe-honest-answer-2026-place-buenavista.webp
is-barranquilla-safe-honest-answer-2026-place-centro-historico.jpg
is-barranquilla-safe-honest-answer-2026-place-centro-historico.webp
is-barranquilla-safe-honest-answer-2026-place-ciudad-jardin.jpg
is-barranquilla-safe-honest-answer-2026-place-ciudad-jardin.webp
is-barranquilla-safe-honest-answer-2026-place-colombia.jpg
is-barranquilla-safe-honest-answer-2026-place-colombia.webp
is-barranquilla-safe-honest-answer-2026-place-el-golf.jpg
is-barranquilla-safe-honest-answer-2026-place-el-golf.webp
is-barranquilla-safe-honest-answer-2026-place-el-prado.jpg
is-barranquilla-safe-honest-answer-2026-place-el-prado.webp
is-barranquilla-safe-honest-answer-2026-place-el-recreo.jpg
is-barranquilla-safe-honest-answer-2026-place-el-recreo.webp
is-barranquilla-safe-honest-answer-2026-place-la-chinita.jpg
is-barranquilla-safe-honest-answer-2026-place-la-chinita.webp
is-barranquilla-safe-honest-answer-2026-place-las-americas.jpg
is-barranquilla-safe-honest-answer-2026-place-las-americas.webp
is-barranquilla-safe-honest-answer-2026-place-localidades-sur-occidente.jpg
is-barranquilla-safe-honest-answer-2026-place-localidades-sur-occidente.webp
is-barranquilla-safe-honest-answer-2026-place-metropolitana.jpg
is-barranquilla-safe-honest-answer-2026-place-metropolitana.webp
is-barranquilla-safe-honest-answer-2026-place-rebolo.jpg
is-barranquilla-safe-honest-answer-2026-place-rebolo.webp
is-barranquilla-safe-honest-answer-2026-place-riomar.jpg
is-barranquilla-safe-honest-answer-2026-place-riomar.webp
is-barranquilla-safe-honest-answer-2026-place-san-roque.jpg
is-barranquilla-safe-honest-answer-2026-place-san-roque.webp
is-barranquilla-safe-honest-answer-2026-place-sur-oriente.jpg
is-barranquilla-safe-honest-answer-2026-place-sur-oriente.webp
is-barranquilla-safe-honest-answer-2026-place-transmetro.jpg
is-barranquilla-safe-honest-answer-2026-place-transmetro.webp
is-barranquilla-safe-honest-answer-2026-place-villa-campestre.jpg
is-barranquilla-safe-honest-answer-2026-place-villa-campestre.webp
is-barranquilla-safe-honest-answer-2026-place-villa-country.jpg
is-barranquilla-safe-honest-answer-2026-place-villa-country.webp
is-barranquilla-safe-honest-answer-2026-place-villa-santos.jpg
is-barranquilla-safe-honest-answer-2026-place-villa-santos.webp
la-castellana-place-el-golf.jpg
la-castellana-place-el-golf.webp
la-castellana-place-la-castellana.jpg
la-castellana-place-la-castellana.webp
la-castellana-place-villa-santos.jpg
la-castellana-place-villa-santos.webp
la-castellana-place-zona-norte.jpg
la-castellana-place-zona-norte.webp
la-ruta-del-girasol-the-sunflower-fields-place-atlantico-department.jpg
la-ruta-del-girasol-the-sunflower-fields-place-atlantico-department.webp
la-ruta-del-girasol-the-sunflower-fields-place-baranoa.jpg
la-ruta-del-girasol-the-sunflower-fields-place-baranoa.webp
la-ruta-del-girasol-the-sunflower-fields-place-barranquilla.jpg
la-ruta-del-girasol-the-sunflower-fields-place-barranquilla.webp
la-ruta-del-girasol-the-sunflower-fields-place-galapa.jpg
la-ruta-del-girasol-the-sunflower-fields-place-galapa.webp
la-ruta-del-girasol-the-sunflower-fields-place-la-ruta-del-girasol.jpg
la-ruta-del-girasol-the-sunflower-fields-place-la-ruta-del-girasol.webp
la-ruta-del-girasol-the-sunflower-fields-place-malambo.jpg
la-ruta-del-girasol-the-sunflower-fields-place-malambo.webp
la-ruta-del-girasol-the-sunflower-fields-place-piojo.jpg
la-ruta-del-girasol-the-sunflower-fields-place-piojo.webp
la-ruta-del-girasol-the-sunflower-fields-place-pital-de-megua.jpg
la-ruta-del-girasol-the-sunflower-fields-place-pital-de-megua.webp
la-ruta-del-girasol-the-sunflower-fields-place-puerto-colombia.jpg
la-ruta-del-girasol-the-sunflower-fields-place-puerto-colombia.webp
la-ruta-del-girasol-the-sunflower-fields-place-sabanalarga.jpg
la-ruta-del-girasol-the-sunflower-fields-place-sabanalarga.webp
la-ruta-del-girasol-the-sunflower-fields-place-santo-tomas.jpg
la-ruta-del-girasol-the-sunflower-fields-place-santo-tomas.webp
la-ruta-del-girasol-the-sunflower-fields-place-troncal-del-caribe.jpg
la-ruta-del-girasol-the-sunflower-fields-place-troncal-del-caribe.webp
la-ruta-del-girasol-the-sunflower-fields-place-usiacuri.jpg
la-ruta-del-girasol-the-sunflower-fields-place-usiacuri.webp
marriott-hotel-barranquilla-place-buenavista.jpg
marriott-hotel-barranquilla-place-buenavista.webp
marriott-hotel-barranquilla-place-el-prado.jpg
marriott-hotel-barranquilla-place-el-prado.webp
marriott-hotel-barranquilla-place-ernesto-cortissoz-airport.jpg
marriott-hotel-barranquilla-place-ernesto-cortissoz-airport.webp
marriott-hotel-barranquilla-place-gran-malecon.jpg
marriott-hotel-barranquilla-place-gran-malecon.webp
marriott-hotel-barranquilla-place-san-basilio-de-palenque.jpg
marriott-hotel-barranquilla-place-san-basilio-de-palenque.webp
miramar-place-calle-84-93-corridor.jpg
miramar-place-calle-84-93-corridor.webp
miramar-place-ciudad-jardin.jpg
miramar-place-ciudad-jardin.webp
miramar-place-el-prado.jpg
miramar-place-el-prado.webp
miramar-place-miramar.jpg
miramar-place-miramar.webp
miramar-place-riomar.jpg
miramar-place-riomar.webp
miramar-place-villa-santos.jpg
miramar-place-villa-santos.webp
moving-to-barranquilla-place-alto-prado.jpg
moving-to-barranquilla-place-alto-prado.webp
moving-to-barranquilla-place-prado.jpg
moving-to-barranquilla-place-prado.webp
moving-to-barranquilla-place-riomar.jpg
moving-to-barranquilla-place-riomar.webp
moving-to-barranquilla-place-villa-country.jpg
moving-to-barranquilla-place-villa-country.webp
nautical-sports-center-salinas-place-atlantico.jpg
nautical-sports-center-salinas-place-atlantico.webp
nautical-sports-center-salinas-place-barranquilla.jpg
nautical-sports-center-salinas-place-barranquilla.webp
neighborhoods-place-alto-prado.jpg
neighborhoods-place-alto-prado.webp
neighborhoods-place-altos-de-riomar.jpg
neighborhoods-place-altos-de-riomar.webp
neighborhoods-place-buenavista.jpg
neighborhoods-place-buenavista.webp
neighborhoods-place-ciudad-jardin.jpg
neighborhoods-place-ciudad-jardin.webp
neighborhoods-place-el-prado.jpg
neighborhoods-place-el-prado.webp
neighborhoods-place-el-tabor.jpg
neighborhoods-place-el-tabor.webp
neighborhoods-place-la-castellana.jpg
neighborhoods-place-la-castellana.webp
neighborhoods-place-puerto-colombia.jpg
neighborhoods-place-puerto-colombia.webp
neighborhoods-place-villa-country.jpg
neighborhoods-place-villa-country.webp
neighborhoods-place-villa-santos.jpg
neighborhoods-place-villa-santos.webp
order-from-amazon-to-colombia-place-barranquilla.jpg
order-from-amazon-to-colombia-place-barranquilla.webp
paraiso-place-calle-76-82.jpg
paraiso-place-calle-76-82.webp
paraiso-place-carrera-53.jpg
paraiso-place-carrera-53.webp
paraiso-place-el-golf.jpg
paraiso-place-el-golf.webp
paraiso-place-paraiso.jpg
paraiso-place-paraiso.webp
paraiso-place-villa-santos.jpg
paraiso-place-villa-santos.webp
pets-mascotas-barranquilla-2026-place-cartagena.jpg
pets-mascotas-barranquilla-2026-place-cartagena.webp
pets-mascotas-barranquilla-2026-place-ciudad-jardin.jpg
pets-mascotas-barranquilla-2026-place-ciudad-jardin.webp
pets-mascotas-barranquilla-2026-place-el-prado.jpg
pets-mascotas-barranquilla-2026-place-el-prado.webp
pets-mascotas-barranquilla-2026-place-gran-malecon-del-rio.jpg
pets-mascotas-barranquilla-2026-place-gran-malecon-del-rio.webp
pets-mascotas-barranquilla-2026-place-minca.jpg
pets-mascotas-barranquilla-2026-place-minca.webp
pets-mascotas-barranquilla-2026-place-parque-venezuela.jpg
pets-mascotas-barranquilla-2026-place-parque-venezuela.webp
pets-mascotas-barranquilla-2026-place-puerto-colombia.jpg
pets-mascotas-barranquilla-2026-place-puerto-colombia.webp
pets-mascotas-barranquilla-2026-place-salgar-beach.jpg
pets-mascotas-barranquilla-2026-place-salgar-beach.webp
pets-mascotas-barranquilla-2026-place-santa-marta.jpg
pets-mascotas-barranquilla-2026-place-santa-marta.webp
pets-mascotas-barranquilla-2026-place-tayrona-national-park.jpg
pets-mascotas-barranquilla-2026-place-tayrona-national-park.webp
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-alto-prado.jpg
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-alto-prado.webp
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-barranquilla.jpg
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-barranquilla.webp
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-riomar.jpg
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-riomar.webp
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-villa-country.jpg
plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-villa-country.webp
puerto-colombia-food-arroz-con-coco.jpg
puerto-colombia-food-arroz-con-coco.webp
puerto-colombia-place-atlantic-coast.jpg
puerto-colombia-place-atlantic-coast.webp
puerto-colombia-place-barranquilla.jpg
puerto-colombia-place-barranquilla.webp
puerto-colombia-place-magdalena-river.jpg
puerto-colombia-place-magdalena-river.webp
puerto-colombia-place-playa-miramar.jpg
puerto-colombia-place-playa-miramar.webp
puerto-colombia-place-playa-pradomar.jpg
puerto-colombia-place-playa-pradomar.webp
puerto-colombia-place-puerto-colombia.jpg
puerto-colombia-place-puerto-colombia.webp
puerto-colombia-place-salgar.jpg
puerto-colombia-place-salgar.webp
puerto-mocho-place-caribbean-sea.jpg
puerto-mocho-place-caribbean-sea.webp
puerto-mocho-place-gran-malecon.jpg
puerto-mocho-place-gran-malecon.webp
puerto-mocho-place-las-flores-neighborhood.jpg
puerto-mocho-place-las-flores-neighborhood.webp
puerto-mocho-place-magdalena-river.jpg
puerto-mocho-place-magdalena-river.webp
puerto-mocho-place-puerto-colombia.jpg
puerto-mocho-place-puerto-colombia.webp
puerto-mocho-place-puerto-mocho.jpg
puerto-mocho-place-puerto-mocho.webp
puerto-mocho-place-riomar-locality.jpg
puerto-mocho-place-riomar-locality.webp
puerto-mocho-place-salgar.jpg
puerto-mocho-place-salgar.webp
puerto-mocho-place-santa-marta.jpg
puerto-mocho-place-santa-marta.webp
riomar-place-el-prado.jpg
riomar-place-el-prado.webp
riomar-place-riomar.jpg
riomar-place-riomar.webp
salary-for-colombian-maid-or-domestic-worker-place-barranquilla.jpg
salary-for-colombian-maid-or-domestic-worker-place-barranquilla.webp
san-basilio-de-palenque-food-fried-red-snapper-with-coconut-rice-and-mango-sauce.jpg
san-basilio-de-palenque-food-fried-red-snapper-with-coconut-rice-and-mango-sauce.webp
san-basilio-de-palenque-place-barranquilla.jpg
san-basilio-de-palenque-place-barranquilla.webp
san-basilio-de-palenque-place-cartagena.jpg
san-basilio-de-palenque-place-cartagena.webp
san-basilio-de-palenque-place-magdalena-river.jpg
san-basilio-de-palenque-place-magdalena-river.webp
san-basilio-de-palenque-place-montes-de-maria.jpg
san-basilio-de-palenque-place-montes-de-maria.webp
san-basilio-de-palenque-place-port-of-cartagena.jpg
san-basilio-de-palenque-place-port-of-cartagena.webp
san-basilio-de-palenque-place-san-basilio-de-palenque.jpg
san-basilio-de-palenque-place-san-basilio-de-palenque.webp
start-small-business-barranquilla-2026-guide-place-barrio-las-flores.jpg
start-small-business-barranquilla-2026-guide-place-barrio-las-flores.webp
start-small-business-barranquilla-2026-guide-place-la-castellana.jpg
start-small-business-barranquilla-2026-guide-place-la-castellana.webp
start-small-business-barranquilla-2026-guide-place-soledad.jpg
start-small-business-barranquilla-2026-guide-place-soledad.webp
study-spanish-in-barranquilla-place-puerto-colombia.jpg
study-spanish-in-barranquilla-place-puerto-colombia.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-arepas.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-arepas.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-bunuelo.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-bunuelo.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-pan-de-yuca.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-pan-de-yuca.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-pandebono.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-food-pandebono.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-alto-prado.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-alto-prado.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-avenida-murillo-via-40.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-avenida-murillo-via-40.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-buenavista-mall.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-buenavista-mall.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-el-prado.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-el-prado.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-granabastos.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-granabastos.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-de-pescados-de-las-flores.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-de-pescados-de-las-flores.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-publico-de-barranquilla.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-publico-de-barranquilla.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-plazas-campesinas.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-plazas-campesinas.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-portal-del-prado-mall.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-portal-del-prado-mall.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-riomar.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-riomar.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-unico-outlet.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-unico-outlet.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-villa-country.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-villa-country.webp
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-viva-barranquilla-mall.jpg
supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-viva-barranquilla-mall.webp
tax-residency-colombia-2026-guide-pexels-generic.jpg
tax-residency-colombia-2026-guide-place-barranquilla.jpg
tax-residency-colombia-2026-guide-place-barranquilla.webp
the-best-hotels-in-barranquilla-place-bello-horizonte.jpg
the-best-hotels-in-barranquilla-place-bello-horizonte.webp
the-best-hotels-in-barranquilla-place-country-club-district.jpg
the-best-hotels-in-barranquilla-place-country-club-district.webp
the-best-hotels-in-barranquilla-place-el-prado-neighborhood.jpg
the-best-hotels-in-barranquilla-place-el-prado-neighborhood.webp
the-best-hotels-in-barranquilla-place-zona-norte.jpg
the-best-hotels-in-barranquilla-place-zona-norte.webp
villa-country-place-carrera-53.jpg
villa-country-place-carrera-53.webp
villa-country-place-villa-country.jpg
villa-country-place-villa-country.webp
villa-country-place-zona-norte.jpg
villa-country-place-zona-norte.webp
villa-santos-place-country-club-corridor.jpg
villa-santos-place-country-club-corridor.webp
villa-santos-place-el-prado.jpg
villa-santos-place-el-prado.webp
villa-santos-place-villa-country.jpg
villa-santos-place-villa-country.webp
villa-santos-place-villa-santos.jpg
villa-santos-place-villa-santos.webp
visas-colombia-barranquilla-place-barrio-el-prado.jpg
visas-colombia-barranquilla-place-barrio-el-prado.webp
whats-happening-barranquilla-april-13-2026-place-malecon.jpg
whats-happening-barranquilla-april-13-2026-place-malecon.webp
FILES

mb=$((size_bytes / 1024 / 1024))
echo "Moved $moved AI image files (~${mb} MB) to: $DEST"
