#!/usr/bin/env bash
# archive-curated-removals.sh
# Moves the 602 files Mike marked Remove in the image-inventory review
# into ~/code/_image-gen/archive/barranquilla/curated-remove/
#
# Usage:  bash scripts/archive-curated-removals.sh

set -e
cd "$(dirname "$0")/.."

DEST="$HOME/code/_image-gen/archive/barranquilla/curated-remove"
mkdir -p "$DEST"

moved=0
size_bytes=0
while IFS= read -r f; do
  [ -z "$f" ] && continue
  if [ -f "$f" ]; then
    sz=$(stat -f%z "$f" 2>/dev/null || stat -c%s "$f" 2>/dev/null || echo 0)
    git rm -q --cached -- "$f" 2>/dev/null || true
    # Use basename in destination (flat dir)
    bn=$(basename "$f")
    mv -- "$f" "$DEST/$bn"
    moved=$((moved + 1))
    size_bytes=$((size_bytes + sz))
  fi
done <<'FILES'
charo-avatar-128.webp
charo-avatar-56.webp
charo-avatar.png
img/barranquilla-airport-guide-place-barranquilla.jpg
img/barranquilla-airport-guide-place-barranquilla.webp
img/barranquilla-airport-guide-place-buenavista.jpg
img/barranquilla-airport-guide-place-buenavista.webp
img/barranquilla-airport-guide-place-cali.jpg
img/barranquilla-airport-guide-place-cali.webp
img/barranquilla-airport-guide-place-cartagena.jpg
img/barranquilla-airport-guide-place-cartagena.webp
img/barranquilla-airport-guide-place-centro-historico.jpg
img/barranquilla-airport-guide-place-centro-historico.webp
img/barranquilla-airport-guide-place-ernesto-cortissoz-international-airport.jpg
img/barranquilla-airport-guide-place-ernesto-cortissoz-international-airport.webp
img/barranquilla-airport-guide-place-fort-lauderdale.jpg
img/barranquilla-airport-guide-place-fort-lauderdale.webp
img/barranquilla-airport-guide-place-malecon.jpg
img/barranquilla-airport-guide-place-malecon.webp
img/barranquilla-airport-guide-place-palomino.jpg
img/barranquilla-airport-guide-place-palomino.webp
img/barranquilla-airport-guide-place-panama-city.jpg
img/barranquilla-airport-guide-place-panama-city.webp
img/barranquilla-airport-guide-place-puerto-colombia.jpg
img/barranquilla-airport-guide-place-puerto-colombia.webp
img/barranquilla-airport-guide-place-san-andres.jpg
img/barranquilla-airport-guide-place-san-andres.webp
img/barranquilla-airport-guide-place-santa-marta.jpg
img/barranquilla-airport-guide-place-santa-marta.webp
img/barranquilla-airport-guide-place-soledad.jpg
img/barranquilla-airport-guide-place-soledad.webp
img/barranquilla-airport-guide-place-tolu.jpg
img/barranquilla-airport-guide-place-tolu.webp
img/barranquilla-airport-guide-place-villa-santos.jpg
img/barranquilla-airport-guide-place-villa-santos.webp
img/barranquilla-bocas-de-cenizas-tour-place-barranquilla.jpg
img/barranquilla-bocas-de-cenizas-tour-place-barranquilla.webp
img/barranquilla-bocas-de-cenizas-tour-place-bocas-de-cenizas.jpg
img/barranquilla-bocas-de-cenizas-tour-place-bocas-de-cenizas.webp
img/barranquilla-bocas-de-cenizas-tour-place-caribbean-sea.jpg
img/barranquilla-bocas-de-cenizas-tour-place-caribbean-sea.webp
img/barranquilla-bocas-de-cenizas-tour-place-cartagena.jpg
img/barranquilla-bocas-de-cenizas-tour-place-cartagena.webp
img/barranquilla-bocas-de-cenizas-tour-place-gran-malecon.jpg
img/barranquilla-bocas-de-cenizas-tour-place-gran-malecon.webp
img/barranquilla-bocas-de-cenizas-tour-place-magdalena-river.jpg
img/barranquilla-bocas-de-cenizas-tour-place-magdalena-river.webp
img/barranquilla-bocas-de-cenizas-tour-place-puerto-colombia.jpg
img/barranquilla-bocas-de-cenizas-tour-place-puerto-colombia.webp
img/barranquilla-bocas-de-cenizas-tour-place-santa-marta.jpg
img/barranquilla-bocas-de-cenizas-tour-place-santa-marta.webp
img/barranquilla-caribbean-night-break-tour-place-el-prado.jpg
img/barranquilla-caribbean-night-break-tour-place-el-prado.webp
img/barranquilla-caribbean-night-break-tour-place-gran-malecon.jpg
img/barranquilla-caribbean-night-break-tour-place-gran-malecon.webp
img/barranquilla-caribbean-night-break-tour-place-puerto-colombia.jpg
img/barranquilla-caribbean-night-break-tour-place-puerto-colombia.webp
img/barranquilla-carnival-complete-guide-place-alto-prado.jpg
img/barranquilla-carnival-complete-guide-place-alto-prado.webp
img/barranquilla-carnival-complete-guide-place-barrio-abajo.jpg
img/barranquilla-carnival-complete-guide-place-barrio-abajo.webp
img/barranquilla-carnival-complete-guide-place-centro.jpg
img/barranquilla-carnival-complete-guide-place-centro.webp
img/barranquilla-carnival-complete-guide-place-villa-country.jpg
img/barranquilla-carnival-complete-guide-place-villa-country.webp
img/barranquilla-guide-place-bello-horizonte.jpg
img/barranquilla-guide-place-bello-horizonte.webp
img/barranquilla-guide-place-el-prado.jpg
img/barranquilla-guide-place-el-prado.webp
img/barranquilla-guide-place-manga.jpg
img/barranquilla-guide-place-manga.webp
img/barranquilla-guide-place-zona-norte.jpg
img/barranquilla-guide-place-zona-norte.webp
img/barranquilla-mallorquin-ecopark-tour-place-bocas-de-cenizas-viewpoint.jpg
img/barranquilla-mallorquin-ecopark-tour-place-bocas-de-cenizas-viewpoint.webp
img/barranquilla-mallorquin-ecopark-tour-place-caribbean-sea.jpg
img/barranquilla-mallorquin-ecopark-tour-place-caribbean-sea.webp
img/barranquilla-mallorquin-ecopark-tour-place-cienaga-grande-ecosystem.jpg
img/barranquilla-mallorquin-ecopark-tour-place-cienaga-grande-ecosystem.webp
img/barranquilla-mallorquin-ecopark-tour-place-magdalena-river.jpg
img/barranquilla-mallorquin-ecopark-tour-place-magdalena-river.webp
img/barranquilla-malls-place-buenavista-corridor.jpg
img/barranquilla-malls-place-buenavista-corridor.webp
img/barranquilla-malls-section-8.jpg
img/barranquilla-malls-section-8.webp
img/barranquilla-nightlife-bars-clubs-place-alto-prado.jpg
img/barranquilla-nightlife-bars-clubs-place-alto-prado.webp
img/barranquilla-nightlife-bars-clubs-place-carrera-43-el-prado.jpg
img/barranquilla-nightlife-bars-clubs-place-carrera-43-el-prado.webp
img/barranquilla-nightlife-bars-clubs-place-centro.jpg
img/barranquilla-nightlife-bars-clubs-place-centro.webp
img/barranquilla-nightlife-bars-clubs-place-el-prado.jpg
img/barranquilla-nightlife-bars-clubs-place-el-prado.webp
img/barranquilla-nightlife-bars-clubs-place-paseo-bolivar.jpg
img/barranquilla-nightlife-bars-clubs-place-paseo-bolivar.webp
img/barranquilla-nightlife-bars-clubs-place-villa-country.jpg
img/barranquilla-nightlife-bars-clubs-place-villa-country.webp
img/barranquilla-private-bike-tour-place-barrio-abajo.jpg
img/barranquilla-private-bike-tour-place-barrio-abajo.webp
img/barranquilla-private-bike-tour-place-el-prado-historic-district.jpg
img/barranquilla-private-bike-tour-place-el-prado-historic-district.webp
img/barranquilla-private-bike-tour-place-gran-malecon-del-rio.jpg
img/barranquilla-private-bike-tour-place-gran-malecon-del-rio.webp
img/barranquilla-private-bike-tour-place-magdalena-river.jpg
img/barranquilla-private-bike-tour-place-magdalena-river.webp
img/barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-alto-prado.jpg
img/barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-alto-prado.webp
img/barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-el-prado.jpg
img/barranquilla-vs-medellin-vs-bogota-which-colombian-city-is-right-for-you-place-el-prado.webp
img/barranquilla-walking-tour-el-prado-place-cartagenas-old-city.jpg
img/barranquilla-walking-tour-el-prado-place-cartagenas-old-city.webp
img/barranquilla-wedding-guide-2026-place-alto-prado.jpg
img/barranquilla-wedding-guide-2026-place-alto-prado.webp
img/barranquilla-wedding-guide-2026-place-gran-malecon-del-rio.jpg
img/barranquilla-wedding-guide-2026-place-gran-malecon-del-rio.webp
img/barranquilla-wedding-guide-2026-place-la-puerta-de-oro.jpg
img/barranquilla-wedding-guide-2026-place-la-puerta-de-oro.webp
img/barranquilla-wedding-guide-2026-place-puerto-colombia.jpg
img/barranquilla-wedding-guide-2026-place-puerto-colombia.webp
img/barranquilla-wedding-guide-2026-place-puerto-velero.jpg
img/barranquilla-wedding-guide-2026-place-puerto-velero.webp
img/barranquilla-wedding-guide-2026-place-tubara.jpg
img/barranquilla-wedding-guide-2026-place-tubara.webp
img/barranquilla-with-kids-family-guide-2026-place-el-golf.jpg
img/barranquilla-with-kids-family-guide-2026-place-el-golf.webp
img/barranquilla-with-kids-family-guide-2026-place-gran-malecon-del-rio.jpg
img/barranquilla-with-kids-family-guide-2026-place-gran-malecon-del-rio.webp
img/barranquilla-with-kids-family-guide-2026-place-parque-metropolitano.jpg
img/barranquilla-with-kids-family-guide-2026-place-parque-metropolitano.webp
img/barranquilla-with-kids-family-guide-2026-place-parque-venezuela.jpg
img/barranquilla-with-kids-family-guide-2026-place-parque-venezuela.webp
img/barranquilla-with-kids-family-guide-2026-place-pradomar.jpg
img/barranquilla-with-kids-family-guide-2026-place-pradomar.webp
img/barranquilla-with-kids-family-guide-2026-place-puerto-colombia.jpg
img/barranquilla-with-kids-family-guide-2026-place-puerto-colombia.webp
img/barranquilla-with-kids-family-guide-2026-place-salgar.jpg
img/barranquilla-with-kids-family-guide-2026-place-salgar.webp
img/barranquilla-with-kids-family-guide-2026-place-santa-marta.jpg
img/barranquilla-with-kids-family-guide-2026-place-santa-marta.webp
img/barranquilla-with-kids-family-guide-2026-place-villa-santos.jpg
img/barranquilla-with-kids-family-guide-2026-place-villa-santos.webp
img/best-coworking-spaces-barranquilla-place-el-poblado.jpg
img/best-coworking-spaces-barranquilla-place-el-poblado.webp
img/best-coworking-spaces-barranquilla-place-el-prado.jpg
img/best-coworking-spaces-barranquilla-place-el-prado.webp
img/best-coworking-spaces-barranquilla-place-zona-norte.jpg
img/best-coworking-spaces-barranquilla-place-zona-norte.webp
img/best-gyms-in-barranquilla-place-alto-prado.jpg
img/best-gyms-in-barranquilla-place-alto-prado.webp
img/best-gyms-in-barranquilla-place-barranquilla.jpg
img/best-gyms-in-barranquilla-place-barranquilla.webp
img/best-gyms-in-barranquilla-place-el-prado.jpg
img/best-gyms-in-barranquilla-place-el-prado.webp
img/best-gyms-in-barranquilla-place-villa-campestre.jpg
img/best-gyms-in-barranquilla-place-villa-campestre.webp
img/best-gyms-in-barranquilla-place-villa-country.jpg
img/best-gyms-in-barranquilla-place-villa-country.webp
img/best-night-out-barranquilla-food-dulcinea.jpg
img/best-night-out-barranquilla-food-dulcinea.webp
img/best-night-out-barranquilla-place-alto-prado.jpg
img/best-night-out-barranquilla-place-alto-prado.webp
img/best-night-out-barranquilla-place-el-prado.jpg
img/best-night-out-barranquilla-place-el-prado.webp
img/best-night-out-barranquilla-place-riomar.jpg
img/best-night-out-barranquilla-place-riomar.webp
img/best-restaurants-with-children-barranquilla-place-gran-malecon.jpg
img/best-restaurants-with-children-barranquilla-place-gran-malecon.webp
img/best-tours-experiences-barranquilla-place-banco-de-la-republica-building.jpg
img/best-tours-experiences-barranquilla-place-banco-de-la-republica-building.webp
img/best-tours-experiences-barranquilla-place-barranquilla.jpg
img/best-tours-experiences-barranquilla-place-barranquilla.webp
img/best-tours-experiences-barranquilla-place-el-centro.jpg
img/best-tours-experiences-barranquilla-place-el-centro.webp
img/best-tours-experiences-barranquilla-place-el-prado-neighbourhood.jpg
img/best-tours-experiences-barranquilla-place-el-prado-neighbourhood.webp
img/best-tours-experiences-barranquilla-place-puerto-colombia.jpg
img/best-tours-experiences-barranquilla-place-puerto-colombia.webp
img/buenavista-place-el-golf.jpg
img/buenavista-place-el-golf.webp
img/buenavista-place-el-prado-neighborhood.jpg
img/buenavista-place-el-prado-neighborhood.webp
img/buenavista-place-puerto-colombia-beaches.jpg
img/buenavista-place-puerto-colombia-beaches.webp
img/buenavista-place-riomar.jpg
img/buenavista-place-riomar.webp
img/buenavista-place-villa-country.jpg
img/buenavista-place-villa-country.webp
img/ciudad-jardin-place-alto-prado.jpg
img/ciudad-jardin-place-alto-prado.webp
img/ciudad-jardin-place-villa-country.jpg
img/ciudad-jardin-place-villa-country.webp
img/colombia-travel-insurance-guide-place-barranquilla.jpg
img/colombia-travel-insurance-guide-place-barranquilla.webp
img/colombia-travel-insurance-guide-place-ernesto-cortissoz-international-airport.jpg
img/colombia-travel-insurance-guide-place-ernesto-cortissoz-international-airport.webp
img/colombia-travel-insurance-guide-place-sierra-nevada.jpg
img/colombia-travel-insurance-guide-place-sierra-nevada.webp
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-alto-prado.jpg
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-alto-prado.webp
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-altos-del-limon.jpg
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-altos-del-limon.webp
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-ciudad-jardin.jpg
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-ciudad-jardin.webp
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-mercado-de-barranquilla.jpg
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-mercado-de-barranquilla.webp
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-country.jpg
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-country.webp
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-santos.jpg
img/cost-of-living-in-barranquilla-a-real-2026-breakdown-place-villa-santos.webp
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-altos-del-prado-barranquilla.jpg
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-altos-del-prado-barranquilla.webp
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-barrio-abajo-barranquilla.jpg
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-barrio-abajo-barranquilla.webp
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-el-prado-barranquilla.jpg
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-el-prado-barranquilla.webp
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-villa-country-barranquilla.jpg
img/dancing-in-barranquilla-salsa-cumbia-champeta-where-to-learn-2026-place-villa-country-barranquilla.webp
img/day-trips-from-barranquilla-place-bocas-de-cenizas.jpg
img/day-trips-from-barranquilla-place-bocas-de-cenizas.webp
img/day-trips-from-barranquilla-place-cartagena.jpg
img/day-trips-from-barranquilla-place-cartagena.webp
img/day-trips-from-barranquilla-place-cienaga-grande-de-santa-marta.jpg
img/day-trips-from-barranquilla-place-cienaga-grande-de-santa-marta.webp
img/day-trips-from-barranquilla-place-nueva-venecia.jpg
img/day-trips-from-barranquilla-place-nueva-venecia.webp
img/day-trips-from-barranquilla-place-puerto-colombia.jpg
img/day-trips-from-barranquilla-place-puerto-colombia.webp
img/day-trips-from-barranquilla-place-santa-marta.jpg
img/day-trips-from-barranquilla-place-santa-marta.webp
img/day-trips-from-barranquilla-place-sierra-nevada-de-santa-marta-mountains.jpg
img/day-trips-from-barranquilla-place-sierra-nevada-de-santa-marta-mountains.webp
img/driving-in-colombia-barranquilla-2026-guide-place-atlantico.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-atlantico.webp
img/driving-in-colombia-barranquilla-2026-guide-place-barranquilla.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-barranquilla.webp
img/driving-in-colombia-barranquilla-2026-guide-place-calle-30.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-calle-30.webp
img/driving-in-colombia-barranquilla-2026-guide-place-calle-84.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-calle-84.webp
img/driving-in-colombia-barranquilla-2026-guide-place-carrera-51b.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-carrera-51b.webp
img/driving-in-colombia-barranquilla-2026-guide-place-pradomar.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-pradomar.webp
img/driving-in-colombia-barranquilla-2026-guide-place-puerto-colombia.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-puerto-colombia.webp
img/driving-in-colombia-barranquilla-2026-guide-place-salgar.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-salgar.webp
img/driving-in-colombia-barranquilla-2026-guide-place-santa-marta.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-santa-marta.webp
img/driving-in-colombia-barranquilla-2026-guide-place-via-40.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-via-40.webp
img/driving-in-colombia-barranquilla-2026-guide-place-zona-norte.jpg
img/driving-in-colombia-barranquilla-2026-guide-place-zona-norte.webp
img/el-golf-place-el-golf.jpg
img/el-golf-place-el-golf.webp
img/el-golf-place-el-prado.jpg
img/el-golf-place-el-prado.webp
img/el-prado-hotel-place-buenavista.jpg
img/el-prado-hotel-place-buenavista.webp
img/el-prado-hotel-place-carrera-53.jpg
img/el-prado-hotel-place-carrera-53.webp
img/el-prado-hotel-place-el-prado-neighborhood.jpg
img/el-prado-hotel-place-el-prado-neighborhood.webp
img/el-prado-hotel-place-via-40.jpg
img/el-prado-hotel-place-via-40.webp
img/el-prado-place-barrio-abajo.jpg
img/el-prado-place-barrio-abajo.webp
img/el-prado-place-el-prado.jpg
img/el-prado-place-el-prado.webp
img/el-tabor-place-buenavista.jpg
img/el-tabor-place-buenavista.webp
img/el-tabor-place-calle-72.jpg
img/el-tabor-place-calle-72.webp
img/el-tabor-place-carrera-46.jpg
img/el-tabor-place-carrera-46.webp
img/el-tabor-place-el-golf.jpg
img/el-tabor-place-el-golf.webp
img/el-tabor-place-el-tabor.jpg
img/el-tabor-place-el-tabor.webp
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-el-prado-neighborhood.jpg
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-el-prado-neighborhood.webp
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-malecon.jpg
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-malecon.webp
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-parque-metropolitano.jpg
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-parque-metropolitano.webp
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-villa-country-neighborhood.jpg
img/expat-networking-social-life-in-barranquilla-how-to-build-your-circle-2026-place-villa-country-neighborhood.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-alameda-del-rio.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-alameda-del-rio.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-bocas-de-ceniza.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-bocas-de-ceniza.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-el-prado.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-el-prado.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-magdalena.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-magdalena.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-plaza-de-la-paz.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-plaza-de-la-paz.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-puerto-colombia.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-puerto-colombia.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-puerto-mocho-beach.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-puerto-mocho-beach.webp
img/fun-things-to-do-in-barranquilla-as-a-group-place-villa-country.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-place-villa-country.webp
img/fun-things-to-do-in-barranquilla-as-a-group-section-7.jpg
img/fun-things-to-do-in-barranquilla-as-a-group-section-7.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-cartagena.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-cartagena.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-catedral-metropolitana.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-catedral-metropolitana.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-downtown-barranquilla.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-downtown-barranquilla.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-el-prado-area.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-el-prado-area.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-gran-malecon-del-rio.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-gran-malecon-del-rio.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-magdalena-river.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-magdalena-river.webp
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-pasaje-bolivar.jpg
img/gran-malecon-carnaval-museum-barranquilla-city-tour-place-pasaje-bolivar.webp
img/healthcare-barranquilla-place-alto-prado.jpg
img/healthcare-barranquilla-place-alto-prado.webp
img/healthcare-barranquilla-place-riomar.jpg
img/healthcare-barranquilla-place-riomar.webp
img/healthcare-barranquilla-place-villa-country.jpg
img/healthcare-barranquilla-place-villa-country.webp
img/healthcare-barranquilla-place-villa-santos.jpg
img/healthcare-barranquilla-place-villa-santos.webp
img/housing-renting-barranquilla-place-alto-prado.jpg
img/housing-renting-barranquilla-place-alto-prado.webp
img/housing-renting-barranquilla-place-altos-de-riomar.jpg
img/housing-renting-barranquilla-place-altos-de-riomar.webp
img/housing-renting-barranquilla-place-altos-del-limon.jpg
img/housing-renting-barranquilla-place-altos-del-limon.webp
img/housing-renting-barranquilla-place-buenavista.jpg
img/housing-renting-barranquilla-place-buenavista.webp
img/housing-renting-barranquilla-place-el-prado.jpg
img/housing-renting-barranquilla-place-el-prado.webp
img/housing-renting-barranquilla-place-granadillo.jpg
img/housing-renting-barranquilla-place-granadillo.webp
img/housing-renting-barranquilla-place-nuevo-horizonte.jpg
img/housing-renting-barranquilla-place-nuevo-horizonte.webp
img/housing-renting-barranquilla-place-paraiso.jpg
img/housing-renting-barranquilla-place-paraiso.webp
img/housing-renting-barranquilla-place-riomar.jpg
img/housing-renting-barranquilla-place-riomar.webp
img/housing-renting-barranquilla-place-via-40.jpg
img/housing-renting-barranquilla-place-via-40.webp
img/housing-renting-barranquilla-place-villa-campestre.jpg
img/housing-renting-barranquilla-place-villa-campestre.webp
img/housing-renting-barranquilla-place-villa-country.jpg
img/housing-renting-barranquilla-place-villa-country.webp
img/housing-renting-barranquilla-place-villa-santos.jpg
img/housing-renting-barranquilla-place-villa-santos.webp
img/is-barranquilla-safe-honest-answer-2026-place-alto-prado.jpg
img/is-barranquilla-safe-honest-answer-2026-place-alto-prado.webp
img/is-barranquilla-safe-honest-answer-2026-place-altos-del-limon.jpg
img/is-barranquilla-safe-honest-answer-2026-place-altos-del-limon.webp
img/is-barranquilla-safe-honest-answer-2026-place-barrio-abajo.jpg
img/is-barranquilla-safe-honest-answer-2026-place-barrio-abajo.webp
img/is-barranquilla-safe-honest-answer-2026-place-boston.jpg
img/is-barranquilla-safe-honest-answer-2026-place-boston.webp
img/is-barranquilla-safe-honest-answer-2026-place-buenavista.jpg
img/is-barranquilla-safe-honest-answer-2026-place-buenavista.webp
img/is-barranquilla-safe-honest-answer-2026-place-centro-historico.jpg
img/is-barranquilla-safe-honest-answer-2026-place-centro-historico.webp
img/is-barranquilla-safe-honest-answer-2026-place-ciudad-jardin.jpg
img/is-barranquilla-safe-honest-answer-2026-place-ciudad-jardin.webp
img/is-barranquilla-safe-honest-answer-2026-place-colombia.jpg
img/is-barranquilla-safe-honest-answer-2026-place-colombia.webp
img/is-barranquilla-safe-honest-answer-2026-place-el-golf.jpg
img/is-barranquilla-safe-honest-answer-2026-place-el-golf.webp
img/is-barranquilla-safe-honest-answer-2026-place-el-prado.jpg
img/is-barranquilla-safe-honest-answer-2026-place-el-prado.webp
img/is-barranquilla-safe-honest-answer-2026-place-el-recreo.jpg
img/is-barranquilla-safe-honest-answer-2026-place-el-recreo.webp
img/is-barranquilla-safe-honest-answer-2026-place-la-chinita.jpg
img/is-barranquilla-safe-honest-answer-2026-place-la-chinita.webp
img/is-barranquilla-safe-honest-answer-2026-place-las-americas.jpg
img/is-barranquilla-safe-honest-answer-2026-place-las-americas.webp
img/is-barranquilla-safe-honest-answer-2026-place-metropolitana.jpg
img/is-barranquilla-safe-honest-answer-2026-place-metropolitana.webp
img/is-barranquilla-safe-honest-answer-2026-place-rebolo.jpg
img/is-barranquilla-safe-honest-answer-2026-place-rebolo.webp
img/is-barranquilla-safe-honest-answer-2026-place-riomar.jpg
img/is-barranquilla-safe-honest-answer-2026-place-riomar.webp
img/is-barranquilla-safe-honest-answer-2026-place-san-roque.jpg
img/is-barranquilla-safe-honest-answer-2026-place-san-roque.webp
img/is-barranquilla-safe-honest-answer-2026-place-sur-oriente.jpg
img/is-barranquilla-safe-honest-answer-2026-place-sur-oriente.webp
img/is-barranquilla-safe-honest-answer-2026-place-transmetro.jpg
img/is-barranquilla-safe-honest-answer-2026-place-transmetro.webp
img/is-barranquilla-safe-honest-answer-2026-place-villa-campestre.jpg
img/is-barranquilla-safe-honest-answer-2026-place-villa-campestre.webp
img/is-barranquilla-safe-honest-answer-2026-place-villa-country.jpg
img/is-barranquilla-safe-honest-answer-2026-place-villa-country.webp
img/is-barranquilla-safe-honest-answer-2026-place-villa-santos.jpg
img/is-barranquilla-safe-honest-answer-2026-place-villa-santos.webp
img/la-castellana-place-el-golf.jpg
img/la-castellana-place-el-golf.webp
img/la-castellana-place-la-castellana.jpg
img/la-castellana-place-la-castellana.webp
img/la-castellana-place-villa-santos.jpg
img/la-castellana-place-villa-santos.webp
img/la-castellana-place-zona-norte.jpg
img/la-castellana-place-zona-norte.webp
img/la-ruta-del-girasol-the-sunflower-fields-place-atlantico-department.jpg
img/la-ruta-del-girasol-the-sunflower-fields-place-atlantico-department.webp
img/la-ruta-del-girasol-the-sunflower-fields-place-baranoa.jpg
img/la-ruta-del-girasol-the-sunflower-fields-place-baranoa.webp
img/la-ruta-del-girasol-the-sunflower-fields-place-barranquilla.jpg
img/la-ruta-del-girasol-the-sunflower-fields-place-barranquilla.webp
img/la-ruta-del-girasol-the-sunflower-fields-place-galapa.jpg
img/la-ruta-del-girasol-the-sunflower-fields-place-galapa.webp
img/la-ruta-del-girasol-the-sunflower-fields-place-malambo.jpg
img/la-ruta-del-girasol-the-sunflower-fields-place-malambo.webp
img/la-ruta-del-girasol-the-sunflower-fields-place-puerto-colombia.jpg
img/la-ruta-del-girasol-the-sunflower-fields-place-puerto-colombia.webp
img/marriott-hotel-barranquilla-place-buenavista.jpg
img/marriott-hotel-barranquilla-place-buenavista.webp
img/marriott-hotel-barranquilla-place-el-prado.jpg
img/marriott-hotel-barranquilla-place-el-prado.webp
img/marriott-hotel-barranquilla-place-ernesto-cortissoz-airport.jpg
img/marriott-hotel-barranquilla-place-ernesto-cortissoz-airport.webp
img/miramar-place-calle-84-93-corridor.jpg
img/miramar-place-calle-84-93-corridor.webp
img/miramar-place-ciudad-jardin.jpg
img/miramar-place-ciudad-jardin.webp
img/miramar-place-el-prado.jpg
img/miramar-place-el-prado.webp
img/miramar-place-miramar.jpg
img/miramar-place-miramar.webp
img/miramar-place-riomar.jpg
img/miramar-place-riomar.webp
img/miramar-place-villa-santos.jpg
img/miramar-place-villa-santos.webp
img/moving-to-barranquilla-place-alto-prado.jpg
img/moving-to-barranquilla-place-alto-prado.webp
img/moving-to-barranquilla-place-prado.jpg
img/moving-to-barranquilla-place-prado.webp
img/moving-to-barranquilla-place-riomar.jpg
img/moving-to-barranquilla-place-riomar.webp
img/nautical-sports-center-salinas-place-atlantico.jpg
img/nautical-sports-center-salinas-place-atlantico.webp
img/nautical-sports-center-salinas-place-barranquilla.jpg
img/nautical-sports-center-salinas-place-barranquilla.webp
img/neighborhoods-place-alto-prado.jpg
img/neighborhoods-place-alto-prado.webp
img/neighborhoods-place-altos-de-riomar.jpg
img/neighborhoods-place-altos-de-riomar.webp
img/neighborhoods-place-buenavista.jpg
img/neighborhoods-place-buenavista.webp
img/neighborhoods-place-ciudad-jardin.jpg
img/neighborhoods-place-ciudad-jardin.webp
img/neighborhoods-place-el-prado.jpg
img/neighborhoods-place-el-prado.webp
img/neighborhoods-place-el-tabor.jpg
img/neighborhoods-place-el-tabor.webp
img/neighborhoods-place-la-castellana.jpg
img/neighborhoods-place-la-castellana.webp
img/neighborhoods-place-puerto-colombia.jpg
img/neighborhoods-place-puerto-colombia.webp
img/neighborhoods-place-villa-country.jpg
img/neighborhoods-place-villa-country.webp
img/neighborhoods-place-villa-santos.jpg
img/neighborhoods-place-villa-santos.webp
img/order-from-amazon-to-colombia-place-barranquilla.jpg
img/order-from-amazon-to-colombia-place-barranquilla.webp
img/paraiso-place-calle-76-82.jpg
img/paraiso-place-calle-76-82.webp
img/paraiso-place-carrera-53.jpg
img/paraiso-place-carrera-53.webp
img/paraiso-place-el-golf.jpg
img/paraiso-place-el-golf.webp
img/paraiso-place-paraiso.jpg
img/paraiso-place-paraiso.webp
img/paraiso-place-villa-santos.jpg
img/paraiso-place-villa-santos.webp
img/pets-mascotas-barranquilla-2026-place-cartagena.jpg
img/pets-mascotas-barranquilla-2026-place-cartagena.webp
img/pets-mascotas-barranquilla-2026-place-ciudad-jardin.jpg
img/pets-mascotas-barranquilla-2026-place-ciudad-jardin.webp
img/pets-mascotas-barranquilla-2026-place-parque-venezuela.jpg
img/pets-mascotas-barranquilla-2026-place-parque-venezuela.webp
img/pets-mascotas-barranquilla-2026-place-puerto-colombia.jpg
img/pets-mascotas-barranquilla-2026-place-puerto-colombia.webp
img/pets-mascotas-barranquilla-2026-place-salgar-beach.jpg
img/pets-mascotas-barranquilla-2026-place-salgar-beach.webp
img/plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-alto-prado.jpg
img/plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-alto-prado.webp
img/plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-barranquilla.jpg
img/plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-barranquilla.webp
img/plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-riomar.jpg
img/plastic-surgery-in-barranquilla-costs-surgeons-medical-tourism-guide-2026-place-riomar.webp
img/puerto-colombia-place-atlantic-coast.jpg
img/puerto-colombia-place-atlantic-coast.webp
img/puerto-colombia-place-barranquilla.jpg
img/puerto-colombia-place-barranquilla.webp
img/puerto-colombia-place-magdalena-river.jpg
img/puerto-colombia-place-magdalena-river.webp
img/puerto-colombia-place-playa-miramar.jpg
img/puerto-colombia-place-playa-miramar.webp
img/puerto-colombia-place-playa-pradomar.jpg
img/puerto-colombia-place-playa-pradomar.webp
img/puerto-colombia-place-puerto-colombia.jpg
img/puerto-colombia-place-puerto-colombia.webp
img/puerto-colombia-place-salgar.jpg
img/puerto-colombia-place-salgar.webp
img/puerto-mocho-place-caribbean-sea.jpg
img/puerto-mocho-place-caribbean-sea.webp
img/puerto-mocho-place-gran-malecon.jpg
img/puerto-mocho-place-gran-malecon.webp
img/puerto-mocho-place-las-flores-neighborhood.jpg
img/puerto-mocho-place-las-flores-neighborhood.webp
img/puerto-mocho-place-magdalena-river.jpg
img/puerto-mocho-place-magdalena-river.webp
img/puerto-mocho-place-puerto-colombia.jpg
img/puerto-mocho-place-puerto-colombia.webp
img/puerto-mocho-place-puerto-mocho.jpg
img/puerto-mocho-place-puerto-mocho.webp
img/puerto-mocho-place-riomar-locality.jpg
img/puerto-mocho-place-riomar-locality.webp
img/puerto-mocho-place-salgar.jpg
img/puerto-mocho-place-salgar.webp
img/puerto-mocho-place-santa-marta.jpg
img/puerto-mocho-place-santa-marta.webp
img/riomar-place-el-prado.jpg
img/riomar-place-el-prado.webp
img/riomar-place-riomar.jpg
img/riomar-place-riomar.webp
img/salary-for-colombian-maid-or-domestic-worker-place-barranquilla.jpg
img/salary-for-colombian-maid-or-domestic-worker-place-barranquilla.webp
img/san-basilio-de-palenque-place-barranquilla.jpg
img/san-basilio-de-palenque-place-barranquilla.webp
img/san-basilio-de-palenque-place-cartagena.jpg
img/san-basilio-de-palenque-place-cartagena.webp
img/san-basilio-de-palenque-place-magdalena-river.jpg
img/san-basilio-de-palenque-place-magdalena-river.webp
img/san-basilio-de-palenque-place-montes-de-maria.jpg
img/san-basilio-de-palenque-place-montes-de-maria.webp
img/san-basilio-de-palenque-place-port-of-cartagena.jpg
img/san-basilio-de-palenque-place-port-of-cartagena.webp
img/san-basilio-de-palenque-place-san-basilio-de-palenque.jpg
img/san-basilio-de-palenque-place-san-basilio-de-palenque.webp
img/start-small-business-barranquilla-2026-guide-place-barrio-las-flores.jpg
img/start-small-business-barranquilla-2026-guide-place-barrio-las-flores.webp
img/start-small-business-barranquilla-2026-guide-place-la-castellana.jpg
img/start-small-business-barranquilla-2026-guide-place-la-castellana.webp
img/start-small-business-barranquilla-2026-guide-place-soledad.jpg
img/start-small-business-barranquilla-2026-guide-place-soledad.webp
img/study-spanish-in-barranquilla-place-puerto-colombia.jpg
img/study-spanish-in-barranquilla-place-puerto-colombia.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-alto-prado.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-alto-prado.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-avenida-murillo-via-40.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-avenida-murillo-via-40.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-buenavista-mall.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-buenavista-mall.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-el-prado.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-el-prado.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-granabastos.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-granabastos.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-de-pescados-de-las-flores.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-de-pescados-de-las-flores.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-publico-de-barranquilla.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-mercado-publico-de-barranquilla.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-portal-del-prado-mall.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-portal-del-prado-mall.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-riomar.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-riomar.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-unico-outlet.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-unico-outlet.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-villa-country.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-villa-country.webp
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-viva-barranquilla-mall.jpg
img/supermarkets-grocery-shopping-in-barranquilla-the-complete-guide-2026-place-viva-barranquilla-mall.webp
img/tax-residency-colombia-2026-guide-pexels-generic.jpg
img/tax-residency-colombia-2026-guide-place-barranquilla.jpg
img/tax-residency-colombia-2026-guide-place-barranquilla.webp
img/the-best-hotels-in-barranquilla-place-bello-horizonte.jpg
img/the-best-hotels-in-barranquilla-place-bello-horizonte.webp
img/the-best-hotels-in-barranquilla-place-country-club-district.jpg
img/the-best-hotels-in-barranquilla-place-country-club-district.webp
img/the-best-hotels-in-barranquilla-place-el-prado-neighborhood.jpg
img/the-best-hotels-in-barranquilla-place-el-prado-neighborhood.webp
img/the-best-hotels-in-barranquilla-place-zona-norte.jpg
img/the-best-hotels-in-barranquilla-place-zona-norte.webp
img/villa-country-place-carrera-53.jpg
img/villa-country-place-carrera-53.webp
img/villa-country-place-villa-country.jpg
img/villa-country-place-villa-country.webp
img/villa-country-place-zona-norte.jpg
img/villa-country-place-zona-norte.webp
img/villa-santos-place-country-club-corridor.jpg
img/villa-santos-place-country-club-corridor.webp
img/villa-santos-place-el-prado.jpg
img/villa-santos-place-el-prado.webp
img/villa-santos-place-villa-country.jpg
img/villa-santos-place-villa-country.webp
img/villa-santos-place-villa-santos.jpg
img/villa-santos-place-villa-santos.webp
img/whats-happening-barranquilla-april-13-2026-place-malecon.jpg
img/whats-happening-barranquilla-april-13-2026-place-malecon.webp
FILES

mb=$((size_bytes / 1024 / 1024))
echo "Moved $moved files (~${mb} MB) to: $DEST"
